### ISSUE TITLE
[Idea] Availability Button

### ISSUE THREAD

**Issue by rafapuerta** [ellreka/streamdeck-slack-status#4]
Could be really nice to add a button to change availability of the user or even that current buttons could change it alongside changing the status message.

**Comment by rafapuerta** [comment]
Hey, no problem!

Just created a PR to add presence control. Please review and thank you.

**Comment by ellreka** [comment]
v1.0.2 has been released.
Thank you!

https://apps.elgato.com/plugins/net.ellreka.slack-status
