### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by hamadaio** [ellreka/streamdeck-slack-status#5]
I've tried everything to the point but it doesn't work. What am I missing?

**Comment by ellreka** [comment]
@hamadaio 

Please test with the following url to check if there is a problem with the token.

https://api.slack.com/methods/users.profile.set/test

![](https://gyazo.com/d22aeda9b8d5c1f4d32a4ab7549cae7f.png)

**Comment by ellreka** [comment]
Please reopen if the same problem occurs!
